language: java
dist: trusty
addons:
 apt:
  packages:
   - openjdk-8-jdk
jdk:
  - openjdk13
  - oraclejdk12
  - openjdk12
  - oraclejdk11
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - openjdk7

